[build]
  command = "npm run build" # the command you run to build this file
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200